### PR TITLE
upgrade to .net 5.0 

### PR DESCRIPTION
**Pull request by maikebing**

### CODE REVIEW

**Comment by Tanya-Solyanik** [comment]
@maikebing  - I'm curious if you are porting an application that uses Chart to .NET 5.0?

**Comment by maikebing** [comment]
@Tanya-Solyanik  yes!

**Comment by Tanya-Solyanik** [comment]
@maikebing - could you please provide a description for your PR and particularly explain the business need, i.e. what is blocked. This repo is read-only  - see https://github.com/dotnet/winforms-datavisualization/blob/main/README.md, so we need to understand your business case before we triage it.

**Comment by kirsan31** [comment]
@Tanya-Solyanik This pr is that most of the users of winforms-datavisualization must done to use it in core. And it's easy.
But we have more serious problem with chart control - [it's not working with new designer](https://github.com/dotnet/winforms/issues/4023#issuecomment-707564714) :(
**merriemcgaw** made a note about it [here](https://github.com/dotnet/winforms/issues/4122#issuecomment-725798527). He explained why the designer doesn't work and advised not to use it. But we still know nothing what must be done with chart control to work with new designer, and how difficult it is...

**Comment by maikebing** [comment]
We want the old app to be deployed through a self-contained single file generated by .Net 5, and no longer install the .net framework.

**Comment by RussKie** [comment]
Thank you for your contribution and the initiative, but I am afraid we can't accept it for a number of reasons.
This code in this repo is provided as is for reference and migration purposes, and no further work is planed. 

You're welcome to fork the code and migrate it to .NET 5.0 to unblock your projects. You're also welcome to post the link to your fork anyone else who may be interested in this migration.

**Pull request closed without merging**
