### PR TITLE
Accessibility: High Contrast theme support and Focus indicator for Chart control

### PR DESCRIPTION
**Pull request by M-Lipin**
Porting accessibility fixes for issues 826994, 827003: support high contrast themes by Chart control labels (if the colors for labels are not specified explicitly), focus indicator for chart control.

### CODE REVIEW

**Comment by Tanya-Solyanik** [comment]
Thank you, looks good. Had you sent this to Olina to buddy test? Is the fix exactly the same as the desktop one or had you added any additional fixes?

**Comment by zsd4yr** [comment]
It's worth mentioning that since the publishing of this NuGet is manual at the moment, that there is some considerable work to be done to publish these once PRs are merged. 

@OliaG and @merriemcgaw we need to determine the cadence at which this should be done. For instance, should I push this through to the NuGet now or...?

**Comment by merriemcgaw** [comment]
Let's do this once with each .NET Core preview, after the final .NET Core SDK build is confirmed, we can rebuild and publish this NuGet package. Does that work?

**Comment by zsd4yr** [comment]
> Let's do this once with each .NET Core preview, after the final .NET Core SDK build is confirmed, we can rebuild and publish this NuGet package. Does that work?

Added an issue to do this #8

**Comment by M-Lipin** [comment]
> Thank you, looks good. Had you sent this to Olina to buddy test? Is the fix exactly the same as the desktop one or had you added any additional fixes?

Thank for the review! No I did not send for testing yet, but will send today. The fix is exactly the same as the desktop fix, the only difference is that there is no AccessibilityImprovements check and the changes are enabled by default.

**Comment by M-Lipin** [comment]
Submitted the test request.

**Pull request merged**
