### PR TITLE
Migrate to 1ES hosted pools

### PR DESCRIPTION
**Pull request by lpatalas**
Tracking issue: https://github.com/dotnet/core-eng/issues/14276

### CODE REVIEW

**Comment by lpatalas** [comment]
The build errors are the same that we already have in main.

**Comment by lpatalas** [comment]
@RussKie Could we get this merged?

**Comment by dreddy-work** [comment]
@lpatalas /  @RussKie , what is the point in taking this if the repo doesn't build? seems we stopped taking maestro updates resulting outdated scripts here.

**Comment by lpatalas** [comment]
@dreddy-work The only drawback of not merging it is that the original pools will be deprecated soon so if anyone would like to run a build at some future time they will have to make this change. Actually I've stumbled upon this repo because I've seen it being built recently and @RussKie suggested to prepare this change just in case it has to be done again.

**Comment by dreddy-work** [comment]
Okay. We should spend some time and get this repo buildable ( at least locally).

**Pull request merged**
